// src/app/layout.tsx
import type { ReactNode } from "react";
import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import LayoutContent from "@/components/layout-content";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nunitoSans = localFont({
  src: [
    {
      path: "../assets/fonts/nunito-sans-variable.ttf",
      style: "normal",
    },
    {
      path: "../assets/fonts/nunito-sans-italic-variable.ttf",
      style: "italic",
    },
  ],
  variable: "--font-nunito-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={`${nunitoSans.variable} antialiased`}
        suppressHydrationWarning
      >
        {<LayoutContent>{children}</LayoutContent>}
      </body>
    </html>
  );
}
