// src/app/layout.tsx
import type { ReactNode } from "react";
import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import LayoutContent from "@/components/layout-content";

import { getCategories } from "@/lib/get-categories";
import { getCollections } from "@/lib/get-collections";
import { getSizes } from "@/lib/get-sizes";
import { getColors } from "@/lib/get-colors";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nunitoSans = localFont({
  src: [
    {
      path: "../assets/fonts/nunito-sans-variable.ttf",
      style: "normal",
    },
    {
      path: "../assets/fonts/nunito-sans-italic-variable.ttf",
      style: "italic",
    },
  ],
  variable: "--font-nunito-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const results = await Promise.allSettled([
    getCategories(),
    getCollections(),
    getSizes(),
    getColors(),
  ]);

  const categories = results[0].status === "fulfilled" ? results[0].value : [];
  const collections = results[1].status === "fulfilled" ? results[1].value : [];
  const sizes = results[2].status === "fulfilled" ? results[2].value : [];
  const colors = results[3].status === "fulfilled" ? results[3].value : [];

  if (results.some((r) => r.status === "rejected")) {
    console.error(
      "Some initial data failed to load:",
      results
        .filter((r) => r.status === "rejected")
        .map((r) => (r as PromiseRejectedResult).reason),
    );
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={`${nunitoSans.variable} antialiased`}
        suppressHydrationWarning
      >
        {
          <LayoutContent
            initialCategories={categories}
            initialCollections={collections}
            initialSizes={sizes}
            initialColors={colors}
          >
            {children}
          </LayoutContent>
        }
      </body>
    </html>
  );
}
