export const dynamic = "force-dynamic";

import type { Metadata } from "next";
import { SearchClient } from "./search.client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Page() {
  return <SearchClient />;
}
