import ProductInteraction from "@/components/elements/products/product-interaction";
import { findProductBySlug } from "@/lib/products";
import { ProductsType, ProductType } from "@/types";
import { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { describe } from "node:test";

export default async function ProductPage({
    params,
    searchParams,
}: {
    params: { slug?: string | string[] };
    searchParams: Promise<{ size: string; color: string }>;
}) {
    const raw = params.slug;
    const slug = Array.isArray(raw) ? raw[0] : raw;
    if (!slug) return notFound();
    const clean = slug ? decodeURIComponent(slug) : undefined;
    let product: ProductType | undefined = findProductBySlug(clean || "");
    if (!product) return notFound();

    // export const generateMetadata = async ({
    //     params,
    // }: {
    //     params: { slug: string };
    // }) => {
    //     return {
    //         title: product.name,
    //         describe: product.description,
    //     };
    // };
    // export const metadata = {
    //     title: "Create Next App",
    //     description: "Generated by create next app",
    // };

    // selected size and color
    const { size, color } = await searchParams;
    const selectedSize = size || (product.sizes[0] as string);
    const selectedColor = color || (product.colors[0] as string);

    return (
        <div className="mt-8 flex flex-col gap-4 md:gap-6 lg:flex-row">
            {/* IMAGE */}
            <div className="relative aspect-4/5 max-h-max w-full lg:w-5/12">
                <Image
                    src={product.images[selectedColor]}
                    alt={product.slug || product.name}
                    fill
                    className="rounded-xl object-cover"
                />
            </div>
            {/* DETAILS */}
            <div className="flex h-max w-full grow-0 flex-col gap-3.5 p-4 lg:w-7/12">
                <h1 className="text-left text-2xl">{product.name}</h1>
                <p className="text-muted-foreground m-0! leading-normal">
                    {product.description}
                </p>
                <h2 className="m-0! text-2xl leading-normal font-semibold">
                    ${product.price}
                </h2>
                <ProductInteraction
                    product={product}
                    selectedSize={selectedSize}
                    selectedColor={selectedColor}
                />

                {/* CARD INFO */}
                <div className="mt-4 flex items-center gap-2">
                    <Image
                        src="/klarna.png"
                        alt="klarna"
                        width={50}
                        height={25}
                        className="rounded-md"
                    />
                    <Image
                        src="/cards.png"
                        alt="cards"
                        width={50}
                        height={25}
                        className="rounded-md"
                    />
                    <Image
                        src="/stripe.png"
                        alt="stripe"
                        width={50}
                        height={25}
                        className="rounded-md"
                    />
                </div>
                <p className="text-muted-foreground m-0! text-sm leading-normal">
                    By clicking Pay Now, you agree to our{" "}
                    <Link
                        href="/legal/terms"
                        className="hover:text-foreground underline"
                    >
                        Terms and Conditions
                    </Link>{" "}
                    and{" "}
                    <Link
                        href="/legal/privacy"
                        className="hover:text-foreground underline"
                    >
                        Privacy Policy
                    </Link>
                    . You authorize us to charge your selected payment method
                    for the total amount shown. All sales are subject to our
                    return and{" "}
                    <Link
                        href="/legal/refund"
                        className="hover:text-foreground underline"
                    >
                        Refund Policy
                    </Link>
                </p>
            </div>
        </div>
    );
}
